name:                timemap
version:             0.0.7
github:              "athanclark/timemap"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "Copyright (c) 2018 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/timemap#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.8 && < 5
- containers
- focus
- hashable
- list-t
- stm
- stm-containers
- time
- unordered-containers

library:
  source-dirs: src

tests:
  timemap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timemap
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - quickcheck-instances
